import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './Providers'
import { Header } from '@/components/header'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Toaster } from '@/components/ui/sonner'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <ScrollArea className="h-screen w-screen relative">
            <Header />
            {children}
            <Toaster
              position="top-center"
              offset={{ top: '100px'}}
            />
          </ScrollArea>
        </Providers>
      </body>
    </html>
  )
}
